// ============================================================
// Nootropic Stack Builder — data.js
// Sources: PubMed, Examine.com, peer-reviewed pharmacology
// Interactions: Only established mechanisms included.
// If uncertain, left out.
// ============================================================

const CATEGORIES = {
  racetam:   { label: 'Racetam',         color: '#8b5cf6' },
  adaptogen: { label: 'Adaptogen',       color: '#22c55e' },
  choline:   { label: 'Choline Source',  color: '#3b82f6' },
  amino:     { label: 'Amino Acid',      color: '#f59e0b' },
  herb:      { label: 'Herb',            color: '#14b8a6' },
  vitamin:   { label: 'Vitamin/Mineral', color: '#f97316' },
  peptide:   { label: 'Peptide',         color: '#ec4899' },
  other:     { label: 'Other',           color: '#71717a' },
};

const BENEFITS = {
  focus:          { label: 'Focus',           color: '#3b82f6' },
  memory:         { label: 'Memory',          color: '#8b5cf6' },
  mood:           { label: 'Mood',            color: '#22c55e' },
  sleep:          { label: 'Sleep',           color: '#6366f1' },
  anxiety:        { label: 'Anxiety',         color: '#14b8a6' },
  energy:         { label: 'Energy',          color: '#f59e0b' },
  neuroprotection:{ label: 'Neuro­protect.',  color: '#ec4899' },
};

// pillsPerDay = typical capsule/tablet count at standard dose
const NOOTROPICS = [
  // ── RACETAMS ─────────────────────────────────────────────
  {
    id: 'piracetam',
    name: 'Piracetam',
    category: 'racetam',
    benefits: ['memory', 'focus', 'neuroprotection'],
    dose: '1,600–2,400 mg × 2–3/day',
    halfLife: '4–5 h',
    mechanism: 'Positive allosteric modulator of AMPA receptors; enhances acetylcholine utilisation in the hippocampus and improves neuronal membrane fluidity.',
    costRange: [15, 35],
    pillsPerDay: 6,
    notes: 'Requires choline supplementation. Water-soluble; no food needed.',
  },
  {
    id: 'aniracetam',
    name: 'Aniracetam',
    category: 'racetam',
    benefits: ['memory', 'mood', 'anxiety', 'focus'],
    dose: '750 mg × 2/day',
    halfLife: '1–2.5 h',
    mechanism: 'AMPA modulator with additional effects on metabotropic glutamate, serotonin (5-HT2A), and dopamine (D2) receptors — source of its anxiolytic character.',
    costRange: [20, 40],
    pillsPerDay: 2,
    notes: 'Fat-soluble — must be taken with food containing fat.',
  },
  {
    id: 'oxiracetam',
    name: 'Oxiracetam',
    category: 'racetam',
    benefits: ['focus', 'memory', 'energy'],
    dose: '800 mg × 2/day',
    halfLife: '8 h',
    mechanism: 'AMPA and NMDA receptor modulator; mildly stimulating — enhances long-term potentiation and acetylcholine/glutamate release in the hippocampus.',
    costRange: [25, 45],
    pillsPerDay: 2,
    notes: 'Water-soluble. Some users find evening doses disrupt sleep.',
  },
  {
    id: 'pramiracetam',
    name: 'Pramiracetam',
    category: 'racetam',
    benefits: ['memory', 'focus'],
    dose: '400 mg × 2/day',
    halfLife: '5–7 h',
    mechanism: 'Potent AMPA modulator that selectively enhances high-affinity choline uptake (HACU) in the hippocampus — the mechanism most directly linked to memory consolidation.',
    costRange: [35, 65],
    pillsPerDay: 2,
    notes: 'Fat-soluble. Very potent — effective at 10× lower doses than piracetam.',
  },
  {
    id: 'phenylpiracetam',
    name: 'Phenylpiracetam',
    category: 'racetam',
    benefits: ['focus', 'energy', 'mood'],
    dose: '100 mg × 1–2/week',
    halfLife: '3–5 h',
    mechanism: 'Adds a phenyl group to piracetam; has modest dopamine and norepinephrine reuptake inhibition alongside AMPA modulation, producing genuine stimulant effects.',
    costRange: [30, 55],
    pillsPerDay: 1,
    notes: 'WADA-prohibited for athletes. Tolerance develops within 2–3 consecutive days — use sparingly.',
  },
  {
    id: 'noopept',
    name: 'Noopept',
    category: 'peptide',
    benefits: ['memory', 'focus', 'mood', 'neuroprotection', 'anxiety'],
    dose: '10–30 mg × 1–2/day',
    halfLife: '~1 h (active metabolites longer)',
    mechanism: 'Dipeptide analogue of piracetam; crosses the BBB efficiently, modulates AMPA/NMDA receptors, and upregulates BDNF and NGF expression at low doses.',
    costRange: [15, 30],
    pillsPerDay: 1,
    notes: 'Very potent by weight. Often cycled (56 days on, 4 weeks off). Requires choline supplementation.',
  },

  // ── CHOLINE SOURCES ───────────────────────────────────────
  {
    id: 'alpha-gpc',
    name: 'Alpha-GPC',
    category: 'choline',
    benefits: ['memory', 'focus', 'energy'],
    dose: '300–600 mg/day',
    halfLife: '4–6 h',
    mechanism: 'Rapidly delivers choline to the brain after hydrolysis; also stimulates growth hormone release from the anterior pituitary — useful for cognitive and athletic performance.',
    costRange: [20, 45],
    pillsPerDay: 1,
    notes: 'Highest choline content per gram (~40%) of any supplement. First-choice for racetam stacking.',
  },
  {
    id: 'citicoline',
    name: 'Citicoline (CDP-Choline)',
    category: 'choline',
    benefits: ['memory', 'focus', 'neuroprotection', 'mood'],
    dose: '250–500 mg × 2/day',
    halfLife: '~56 h (as choline)',
    mechanism: 'Delivers choline plus cytidine (which converts to uridine in the body); increases phosphatidylcholine synthesis and dopamine receptor density via the Kennedy pathway.',
    costRange: [20, 40],
    pillsPerDay: 2,
    notes: 'Lower choline % than Alpha-GPC but provides additional neuroprotective uridine. Used clinically post-stroke in Europe.',
  },
  {
    id: 'choline-bitartrate',
    name: 'Choline Bitartrate',
    category: 'choline',
    benefits: ['memory', 'focus'],
    dose: '500–1,000 mg/day',
    halfLife: '—',
    mechanism: 'Basic choline salt that raises plasma choline levels; poor blood-brain barrier penetration limits cognitive effectiveness compared to Alpha-GPC or citicoline.',
    costRange: [5, 15],
    pillsPerDay: 2,
    notes: 'Budget option. Significantly less effective than Alpha-GPC or citicoline for brain choline delivery.',
  },

  // ── ADAPTOGENS ────────────────────────────────────────────
  {
    id: 'ashwagandha',
    name: 'Ashwagandha (KSM-66)',
    category: 'adaptogen',
    benefits: ['anxiety', 'mood', 'sleep', 'energy', 'neuroprotection'],
    dose: '300–600 mg/day',
    halfLife: '—',
    mechanism: 'Withanolides reduce cortisol via HPA axis modulation and exert anxiolytic effects through partial GABA-A receptor agonism and serotonin receptor activity.',
    costRange: [15, 35],
    pillsPerDay: 1,
    notes: 'Effects build over 4–8 weeks. Avoid in pregnancy (uterotonic). May interact with thyroid medications.',
  },
  {
    id: 'rhodiola',
    name: 'Rhodiola Rosea',
    category: 'adaptogen',
    benefits: ['energy', 'mood', 'focus', 'anxiety'],
    dose: '200–400 mg/day',
    halfLife: '—',
    mechanism: 'Rosavins and salidroside mildly inhibit MAO-A/B, reduce cortisol via Hsp70 stress-protein regulation, and improve mitochondrial energy efficiency under stress.',
    costRange: [15, 30],
    pillsPerDay: 1,
    notes: 'Take in the morning — activating, may disrupt sleep if taken late. Standardise to 3% rosavins / 1% salidroside.',
  },
  {
    id: 'lions-mane',
    name: "Lion's Mane Mushroom",
    category: 'adaptogen',
    benefits: ['memory', 'neuroprotection', 'mood'],
    dose: '500–1,000 mg × 2/day',
    halfLife: '—',
    mechanism: 'Hericenones (fruiting body) and erinacines (mycelium) stimulate nerve growth factor (NGF) synthesis, promoting neurogenesis and myelin repair.',
    costRange: [20, 45],
    pillsPerDay: 2,
    notes: 'Effects are cumulative — meaningful cognitive effects emerge after 4–8 weeks. Look for fruiting-body extracts.',
  },
  {
    id: 'bacopa',
    name: 'Bacopa Monnieri',
    category: 'adaptogen',
    benefits: ['memory', 'anxiety', 'neuroprotection', 'mood'],
    dose: '300–450 mg/day (55% bacosides)',
    halfLife: '—',
    mechanism: 'Bacosides enhance synaptic signalling, reversibly inhibit acetylcholinesterase, and provide antioxidant protection in the hippocampus.',
    costRange: [15, 30],
    pillsPerDay: 1,
    notes: 'Fat-soluble — take with food. Effects emerge after 8–12 weeks. Best nootropic for long-term memory research.',
  },
  {
    id: 'panax-ginseng',
    name: 'Panax Ginseng',
    category: 'adaptogen',
    benefits: ['focus', 'energy', 'mood', 'memory'],
    dose: '200–400 mg/day',
    halfLife: '—',
    mechanism: 'Ginsenosides modulate GABA, serotonin, and dopamine receptors while reducing HPA axis reactivity and oxidative stress.',
    costRange: [15, 30],
    pillsPerDay: 1,
    notes: 'Standardise to 4–8% ginsenosides. May cause insomnia if taken late.',
  },
  {
    id: 'holy-basil',
    name: 'Holy Basil (Tulsi)',
    category: 'adaptogen',
    benefits: ['anxiety', 'mood', 'neuroprotection'],
    dose: '300–600 mg/day',
    halfLife: '—',
    mechanism: 'Ursolic acid and rosmarinic acid modulate cortisol response, inhibit COX enzymes, and have mild MAO-A inhibitory activity reducing stress-induced monoamine depletion.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Well-tolerated. May mildly lower blood sugar — caution in diabetics.',
  },

  // ── AMINO ACIDS ───────────────────────────────────────────
  {
    id: 'l-theanine',
    name: 'L-Theanine',
    category: 'amino',
    benefits: ['anxiety', 'focus', 'sleep', 'mood'],
    dose: '100–200 mg/dose',
    halfLife: '~1 h',
    mechanism: 'Promotes alpha-wave brain activity; modulates GABA-A, NMDA, and AMPA receptors producing calm focus without sedation. Crosses the BBB within 30 minutes.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Pairs classically with caffeine (2:1 ratio). Very safe; no known serious side effects.',
  },
  {
    id: 'nalt',
    name: 'N-Acetyl L-Tyrosine (NALT)',
    category: 'amino',
    benefits: ['focus', 'energy', 'mood'],
    dose: '300–600 mg/day',
    halfLife: '—',
    mechanism: 'Bioavailable tyrosine form that serves as the direct precursor to dopamine, norepinephrine, and epinephrine via the catecholamine synthesis pathway.',
    costRange: [10, 25],
    pillsPerDay: 1,
    notes: 'Most effective under stress or sleep deprivation. Less effective at baseline high dopamine states.',
  },
  {
    id: 'alcar',
    name: 'Acetyl-L-Carnitine (ALCAR)',
    category: 'amino',
    benefits: ['memory', 'focus', 'neuroprotection', 'energy', 'mood'],
    dose: '500–1,500 mg/day',
    halfLife: '~4 h',
    mechanism: 'Transports long-chain fatty acids into mitochondria for beta-oxidation; the acetyl group also serves as a substrate for acetylcholine synthesis in the CNS.',
    costRange: [15, 30],
    pillsPerDay: 2,
    notes: 'Wide evidence base. Especially useful for age-related cognitive decline.',
  },
  {
    id: '5-htp',
    name: '5-HTP',
    category: 'amino',
    benefits: ['mood', 'anxiety', 'sleep'],
    dose: '50–200 mg/day',
    halfLife: '~2 h',
    mechanism: 'Direct serotonin precursor; crosses the blood-brain barrier and is rapidly decarboxylated to serotonin by aromatic amino acid decarboxylase (AADC).',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Do not combine with MAOIs, SSRIs, or L-Tryptophan (additive serotonergic load). Take with carbidopa to prevent peripheral conversion.',
  },
  {
    id: 'l-tryptophan',
    name: 'L-Tryptophan',
    category: 'amino',
    benefits: ['mood', 'anxiety', 'sleep'],
    dose: '500–2,000 mg/day',
    halfLife: '—',
    mechanism: 'Essential amino acid; upstream serotonin and melatonin precursor via the kynurenine and 5-HTP pathways. Competes with other large neutral amino acids for BBB transport.',
    costRange: [10, 20],
    pillsPerDay: 2,
    notes: 'Take on an empty stomach away from protein meals to maximise BBB uptake. Do not combine with MAOIs.',
  },
  {
    id: 'taurine',
    name: 'Taurine',
    category: 'amino',
    benefits: ['anxiety', 'neuroprotection', 'sleep', 'mood'],
    dose: '500–2,000 mg/day',
    halfLife: '—',
    mechanism: 'Acts as an inhibitory neuromodulator; agonises GABA-A and glycine receptors and reduces glutamate-mediated excitotoxicity.',
    costRange: [8, 18],
    pillsPerDay: 2,
    notes: 'Very well-tolerated. Conditionally essential — production declines with age and under stress.',
  },
  {
    id: 'agmatine',
    name: 'Agmatine Sulfate',
    category: 'amino',
    benefits: ['mood', 'neuroprotection', 'anxiety'],
    dose: '500–2,000 mg/day',
    halfLife: '—',
    mechanism: 'Endogenous neuromodulator derived from arginine; modulates NMDA receptors (as an antagonist), imidazoline receptors, and nitric oxide synthase.',
    costRange: [15, 30],
    pillsPerDay: 2,
    notes: 'Antidepressant-like effects in animal models. Evidence base in humans is still emerging.',
  },

  // ── HERBS ─────────────────────────────────────────────────
  {
    id: 'gotu-kola',
    name: 'Gotu Kola',
    category: 'herb',
    benefits: ['anxiety', 'mood', 'neuroprotection', 'memory'],
    dose: '500–1,000 mg/day',
    halfLife: '—',
    mechanism: 'Asiaticoside and madecassoside promote NGF expression and neurogenesis, reduce anxiety via GABAergic pathways, and enhance antioxidant status in the hippocampus.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Traditional Ayurvedic herb. Mild and well-tolerated. Pairs well with bacopa.',
  },
  {
    id: 'ginkgo-biloba',
    name: 'Ginkgo Biloba',
    category: 'herb',
    benefits: ['focus', 'memory', 'neuroprotection', 'mood'],
    dose: '120–240 mg/day (24% flavone glycosides)',
    halfLife: '~5 h',
    mechanism: 'Ginkgolides inhibit platelet-activating factor (PAF); flavone glycosides reduce oxidative stress and improve cerebral blood flow via nitric oxide pathway modulation.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Mild anticoagulant effect — use caution with blood thinners or before surgery.',
  },
  {
    id: 'vinpocetine',
    name: 'Vinpocetine',
    category: 'herb',
    benefits: ['focus', 'memory', 'neuroprotection'],
    dose: '10–30 mg × 2/day',
    halfLife: '~2 h',
    mechanism: 'Selective inhibitor of PDE1 (phosphodiesterase type 1), raising cAMP and cGMP; improves cerebral blood flow and neuronal glucose/oxygen metabolism.',
    costRange: [15, 30],
    pillsPerDay: 2,
    notes: 'Take with food. Mild blood pressure-lowering effect. Prescription-only in some countries.',
  },
  {
    id: 'saffron',
    name: 'Saffron (Affron)',
    category: 'herb',
    benefits: ['mood', 'anxiety', 'neuroprotection', 'memory'],
    dose: '28–30 mg/day (extract)',
    halfLife: '~2 h',
    mechanism: 'Crocin and safranal weakly inhibit serotonin, dopamine, and norepinephrine reuptake, and modulate NMDA receptor activity — contributing to antidepressant-like effects.',
    costRange: [20, 45],
    pillsPerDay: 1,
    notes: 'Strong evidence for mood support. Use standardised extract (Affron). Very high doses may be emmenagogic.',
  },
  {
    id: 'mucuna-pruriens',
    name: 'Mucuna Pruriens',
    category: 'herb',
    benefits: ['mood', 'focus', 'energy'],
    dose: '300–500 mg (15% L-DOPA extract)',
    halfLife: '~90 min (L-DOPA)',
    mechanism: 'Contains L-DOPA (levodopa) — a direct dopamine precursor that crosses the BBB and raises striatal dopamine via aromatic L-amino acid decarboxylase.',
    costRange: [15, 30],
    pillsPerDay: 1,
    notes: 'Not for daily use long-term due to L-DOPA tolerance risk. Avoid with MAOIs (hypertensive crisis risk).',
  },
  {
    id: 'huperzine-a',
    name: 'Huperzine A',
    category: 'herb',
    benefits: ['memory', 'focus', 'neuroprotection'],
    dose: '50–200 µg/day',
    halfLife: '~10–12 h',
    mechanism: 'Selective, reversible acetylcholinesterase (AChE) inhibitor; elevates acetylcholine levels in the cortex and hippocampus — the same mechanism as prescription Alzheimer\'s drugs.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Long half-life — do not take daily; cycle (5 days on, 2 off). Very easy to overdo cholinergic effects.',
  },

  // ── VITAMINS / MINERALS ───────────────────────────────────
  {
    id: 'magnesium-threonate',
    name: 'Magnesium L-Threonate',
    category: 'vitamin',
    benefits: ['memory', 'sleep', 'neuroprotection', 'anxiety'],
    dose: '1,500–2,000 mg/day (providing ~144 mg Mg)',
    halfLife: '—',
    mechanism: 'The threonate form uniquely raises brain magnesium; Mg²⁺ is an essential NMDA receptor co-factor for synaptic plasticity and long-term potentiation.',
    costRange: [30, 60],
    pillsPerDay: 3,
    notes: 'Other magnesium forms (glycinate, citrate) have poor CNS penetration. Only threonate reliably raises brain Mg.',
  },
  {
    id: 'vitamin-d3',
    name: 'Vitamin D3',
    category: 'vitamin',
    benefits: ['mood', 'neuroprotection', 'energy'],
    dose: '2,000–5,000 IU/day',
    halfLife: '~15 days',
    mechanism: 'Nuclear receptor ligand (VDR) that modulates over 200 genes including those governing dopamine synthesis, neurotrophin expression, and neuroinflammation.',
    costRange: [5, 15],
    pillsPerDay: 1,
    notes: 'Deficiency is widespread and profoundly impacts mood and cognition. Test levels before supplementing high doses.',
  },
  {
    id: 'omega-3',
    name: 'Omega-3 (DHA/EPA)',
    category: 'vitamin',
    benefits: ['memory', 'mood', 'neuroprotection'],
    dose: '1,000–2,000 mg combined DHA+EPA/day',
    halfLife: '—',
    mechanism: 'DHA is a structural phospholipid of neuronal membranes; EPA reduces neuroinflammation via eicosanoid modulation. Both support BDNF expression.',
    costRange: [15, 30],
    pillsPerDay: 2,
    notes: 'Take with food. Look for triglyceride form for better absorption. Certified for heavy metals.',
  },
  {
    id: 'zinc',
    name: 'Zinc',
    category: 'vitamin',
    benefits: ['mood', 'neuroprotection', 'sleep'],
    dose: '15–30 mg/day',
    halfLife: '—',
    mechanism: 'Essential cofactor for over 300 enzymes; modulates NMDA and GABA-A receptors, supports neurogenesis, and is required for BDNF signalling.',
    costRange: [5, 15],
    pillsPerDay: 1,
    notes: 'Do not exceed 40 mg/day long-term (copper depletion risk). Take away from other minerals.',
  },
  // ── OTHER ─────────────────────────────────────────────────
  {
    id: 'caffeine',
    name: 'Caffeine',
    category: 'other',
    benefits: ['focus', 'energy'],
    dose: '50–200 mg/dose',
    halfLife: '5–7 h',
    mechanism: 'Competitive adenosine receptor (A1/A2A) antagonist; blocks sleep pressure accumulation while increasing dopamine signalling and acetylcholine release.',
    costRange: [5, 10],
    pillsPerDay: 1,
    notes: 'Most widely used psychoactive substance. Tolerance develops with daily use. Avoid after noon.',
  },
  {
    id: 'modafinil',
    name: 'Modafinil',
    category: 'other',
    benefits: ['focus', 'energy', 'mood'],
    dose: '100–200 mg/morning',
    halfLife: '12–15 h',
    mechanism: 'Inhibits dopamine transporter (DAT) and norepinephrine transporter; activates orexin/hypocretin and histamine wakefulness pathways without major catecholamine flooding.',
    costRange: [50, 150],
    pillsPerDay: 1,
    notes: 'Prescription-only in most countries. Schedule IV (US). Reduces hormonal contraceptive efficacy (CYP3A4 inducer).',
  },
  {
    id: 'sulbutiamine',
    name: 'Sulbutiamine',
    category: 'other',
    benefits: ['memory', 'mood', 'energy'],
    dose: '400–600 mg/day',
    halfLife: '~5 h',
    mechanism: 'Thiamine disulfide derivative with superior BBB penetration; modulates cholinergic and dopaminergic transmission, and raises thiamine pyrophosphate in the brain.',
    costRange: [15, 30],
    pillsPerDay: 2,
    notes: 'Fat-soluble — take with food. Cycle to prevent tolerance. Used for asthenia and memory in Europe.',
  },
  {
    id: 'uridine',
    name: 'Uridine Monophosphate',
    category: 'other',
    benefits: ['mood', 'neuroprotection', 'memory'],
    dose: '150–500 mg/day',
    halfLife: '—',
    mechanism: 'Pyrimidine nucleotide that increases phosphatidylcholine synthesis via the Kennedy pathway and enhances dopamine receptor density and synaptic plasticity.',
    costRange: [20, 40],
    pillsPerDay: 1,
    notes: 'Key compound in the "Mr. Happy Stack" (uridine + alpha-gpc + omega-3). Also supplied by citicoline.',
  },
  {
    id: 'phosphatidylserine',
    name: 'Phosphatidylserine',
    category: 'other',
    benefits: ['memory', 'mood', 'neuroprotection', 'focus'],
    dose: '300–800 mg/day',
    halfLife: '—',
    mechanism: 'Phospholipid component of neuronal cell membranes; supports cortisol regulation under stress and cell signalling at cholinergic and dopaminergic synapses.',
    costRange: [25, 50],
    pillsPerDay: 3,
    notes: 'FDA-qualified health claim for dementia risk reduction. Use soy- or sunflower-derived forms.',
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    category: 'other',
    benefits: ['sleep'],
    dose: '0.5–3 mg, 30–60 min before bed',
    halfLife: '0.5–1 h',
    mechanism: 'Pineal gland hormone that binds MT1/MT2 receptors in the SCN (suprachiasmatic nucleus); shifts circadian phase and exerts direct antioxidant/neuroprotective activity.',
    costRange: [5, 15],
    pillsPerDay: 1,
    notes: 'Lower doses (0.5 mg) are as effective as higher doses for most people. Not for daily long-term use.',
  },
  {
    id: 'gaba',
    name: 'GABA',
    category: 'amino',
    benefits: ['anxiety', 'sleep'],
    dose: '250–750 mg/day',
    halfLife: '—',
    mechanism: 'Endogenous inhibitory neurotransmitter; oral GABA may act peripherally via the enteric nervous system and vagus nerve — direct CNS penetration is debated.',
    costRange: [10, 20],
    pillsPerDay: 1,
    notes: 'Evidence for direct CNS effects is limited. L-Theanine and magnesium have stronger evidence for CNS GABA modulation.',
  },
  {
    id: 'pqq',
    name: 'PQQ (Pyrroloquinoline Quinone)',
    category: 'other',
    benefits: ['energy', 'neuroprotection', 'memory'],
    dose: '10–20 mg/day',
    halfLife: '—',
    mechanism: 'Redox cofactor that stimulates mitochondrial biogenesis via PGC-1α; acts as a potent neuroprotective antioxidant and supports nerve growth factor signalling.',
    costRange: [25, 50],
    pillsPerDay: 1,
    notes: 'Often stacked with CoQ10. Take with food.',
  },
  {
    id: 'creatine',
    name: 'Creatine Monohydrate',
    category: 'other',
    benefits: ['focus', 'energy', 'memory'],
    dose: '3–5 g/day',
    halfLife: '—',
    mechanism: 'Replenishes phosphocreatine in the brain, increasing ATP availability in the energy-demanding prefrontal cortex. Also reduces mental fatigue under cognitive load.',
    costRange: [15, 25],
    pillsPerDay: 5,
    notes: 'One of the most evidence-backed supplements. Very safe. Vegetarians/vegans see larger cognitive benefit (lower baseline).',
  },
  {
    id: 'nmn',
    name: 'NMN (Nicotinamide Mononucleotide)',
    category: 'other',
    benefits: ['energy', 'neuroprotection'],
    dose: '250–500 mg/day',
    halfLife: '~2 h',
    mechanism: 'Direct NAD⁺ precursor; replenishes NAD⁺ pools that decline with age, supporting mitochondrial function, sirtuin activity (DNA repair), and PARP enzyme function.',
    costRange: [40, 100],
    pillsPerDay: 1,
    notes: 'More bioavailable than NR in some studies. Store in cool, dark location. Evidence in humans is still emerging.',
  },
  {
    id: 'pterostilbene',
    name: 'Pterostilbene',
    category: 'other',
    benefits: ['neuroprotection', 'focus', 'mood'],
    dose: '50–150 mg/day',
    halfLife: '~7 h',
    mechanism: 'Potent SIRT1 activator and polyphenol antioxidant — more bioavailable and brain-penetrant than its parent compound resveratrol. Inhibits NF-κB neuroinflammation.',
    costRange: [20, 40],
    pillsPerDay: 1,
    notes: 'Often stacked with NMN/NR (sirtuins require NAD⁺). Preferably taken with food.',
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    category: 'other',
    benefits: ['neuroprotection', 'mood', 'energy'],
    dose: '150–500 mg/day',
    halfLife: '~1–3 h',
    mechanism: 'Polyphenol that activates SIRT1 and AMPK; reduces neuroinflammation via NF-κB inhibition and supports cerebrovascular health and mitochondrial biogenesis.',
    costRange: [15, 35],
    pillsPerDay: 1,
    notes: 'Poor bioavailability — take with fat and piperine. Pterostilbene is a more bioavailable analogue.',
  },
  {
    id: 'semax',
    name: 'Semax',
    category: 'peptide',
    benefits: ['memory', 'focus', 'mood', 'neuroprotection'],
    dose: '200–600 µg intranasally/day',
    halfLife: '~15 min (active metabolites longer)',
    mechanism: 'ACTH(4–7) analogue that increases BDNF, NGF, and CNTF expression; modulates dopamine, serotonin, and melanocortin systems via receptor pathway activation.',
    costRange: [40, 80],
    pillsPerDay: 0,
    notes: 'Intranasal administration (drops). Not widely available outside Russia and grey market. Research mostly from Russian clinical trials.',
  },
];

// ── Deduplicate (vitamin-d3 appeared twice in draft) ─────────
// (already removed duplicate above — final array is clean)

// ============================================================
// INTERACTIONS
// Only established mechanisms are included.
// If evidence is uncertain, the interaction is not listed.
// type: 'synergy' | 'caution' | 'conflict'
// ============================================================
const INTERACTIONS = [

  // ── SYNERGIES ─────────────────────────────────────────────

  // The most replicated nootropic combination in human trials
  { compounds: ['caffeine', 'l-theanine'], type: 'synergy',
    title: 'Classic synergy',
    description: 'L-Theanine blunts caffeine-induced anxiety and jitteriness while preserving wakefulness and focus. Multiple RCTs confirm superior performance vs either compound alone. Use 2:1 Theanine:Caffeine ratio.' },

  // Racetam + choline — essential pairings
  { compounds: ['piracetam', 'alpha-gpc'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Piracetam increases acetylcholine (ACh) demand in the hippocampus. Alpha-GPC rapidly supplies choline for ACh synthesis — preventing depletion, headaches, and blunted effects.' },
  { compounds: ['piracetam', 'citicoline'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Citicoline supplies choline for ACh synthesis alongside neuroprotective uridine. Required when taking piracetam to prevent choline depletion.' },
  { compounds: ['aniracetam', 'alpha-gpc'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Aniracetam raises ACh demand — Alpha-GPC ensures adequate choline supply and prevents the characteristic racetam headache.' },
  { compounds: ['aniracetam', 'citicoline'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Citicoline provides choline plus uridine when stacking with aniracetam, covering both ACh supply and dopamine receptor support.' },
  { compounds: ['oxiracetam', 'alpha-gpc'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Oxiracetam increases hippocampal ACh and glutamate release — Alpha-GPC ensures the choline supply keeps pace.' },
  { compounds: ['oxiracetam', 'citicoline'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Citicoline replenishes choline demand from oxiracetam while contributing neuroprotective uridine.' },
  { compounds: ['pramiracetam', 'alpha-gpc'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Pramiracetam specifically enhances high-affinity choline uptake — making the choline supply from Alpha-GPC especially critical at this compound\'s high potency.' },
  { compounds: ['pramiracetam', 'citicoline'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Citicoline provides choline and uridine to support pramiracetam\'s memory effects and maintain neuronal membrane integrity.' },
  { compounds: ['phenylpiracetam', 'alpha-gpc'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Phenylpiracetam increases ACh demand as part of its AMPA modulation — Alpha-GPC prevents choline depletion.' },
  { compounds: ['phenylpiracetam', 'citicoline'], type: 'synergy',
    title: 'Essential racetam support',
    description: 'Citicoline supplies choline and uridine for phenylpiracetam stacking, reducing side effects from choline depletion.' },
  { compounds: ['noopept', 'alpha-gpc'], type: 'synergy',
    title: 'Cholinergic support for Noopept',
    description: 'Noopept increases ACh receptor sensitivity — Alpha-GPC ensures adequate choline supply to take advantage of this sensitisation.' },
  { compounds: ['noopept', 'citicoline'], type: 'synergy',
    title: 'Cholinergic support for Noopept',
    description: 'Citicoline provides choline and uridine complementing noopept\'s BDNF/NGF-upregulating effects for broader neuroprotection.' },

  // Mr. Happy Stack components
  { compounds: ['uridine', 'alpha-gpc'], type: 'synergy',
    title: '"Mr. Happy Stack" core',
    description: 'Uridine + Alpha-GPC + Omega-3 is a well-documented combination for phosphatidylcholine synthesis in neuronal membranes — supporting mood, neuroplasticity, and dopamine receptor density.' },
  { compounds: ['uridine', 'omega-3'], type: 'synergy',
    title: '"Mr. Happy Stack" core',
    description: 'DHA (omega-3) provides the structural backbone for neuronal membranes while uridine drives phosphatidylcholine synthesis via the Kennedy pathway — synergistic for neuroplasticity.' },

  // Cholinergic support combinations
  { compounds: ['alcar', 'alpha-gpc'], type: 'synergy',
    title: 'Complementary cholinergic support',
    description: 'ALCAR provides the acetyl group for ACh synthesis while Alpha-GPC provides the choline substrate — together they support the entire ACh biosynthetic pathway.' },
  { compounds: ['alcar', 'citicoline'], type: 'synergy',
    title: 'Complementary cholinergic support',
    description: 'ALCAR\'s acetyl donation for ACh synthesis complements citicoline\'s choline supply and uridine-mediated neuroprotection.' },
  { compounds: ['bacopa', 'alpha-gpc'], type: 'synergy',
    title: 'Dual cholinergic support',
    description: 'Bacopa inhibits acetylcholinesterase (slows ACh breakdown) while Alpha-GPC increases ACh supply — together they raise and sustain ACh levels via two different mechanisms.' },
  { compounds: ['bacopa', 'citicoline'], type: 'synergy',
    title: 'Dual cholinergic support',
    description: 'Bacopa\'s AChE inhibition pairs with citicoline\'s choline supply and uridine component for complementary memory and neuroprotective effects.' },

  // Other synergies
  { compounds: ['modafinil', 'l-theanine'], type: 'synergy',
    title: 'Smooths modafinil edge',
    description: 'L-Theanine reduces the anxiety and overstimulation that some users experience with modafinil, without reducing the wakefulness or focus benefit.' },
  { compounds: ['ashwagandha', 'rhodiola'], type: 'synergy',
    title: 'Complementary adaptogens',
    description: 'Ashwagandha addresses chronic stress, cortisol, and sleep (calming adaptogen); rhodiola addresses acute mental fatigue and performance under stress (energising adaptogen). Different mechanisms — work well together.' },
  { compounds: ['phosphatidylserine', 'omega-3'], type: 'synergy',
    title: 'Membrane synergy',
    description: 'Both support neuronal membrane integrity — phosphatidylserine maintains the phospholipid bilayer structure while DHA integrates as a key structural component. Complementary, non-redundant roles.' },
  { compounds: ['lions-mane', 'bacopa'], type: 'synergy',
    title: 'Complementary neuroprotection',
    description: 'Lion\'s mane stimulates NGF for neurogenesis; bacopa provides antioxidant protection and AChE inhibition. Complementary mechanisms targeting different aspects of long-term brain health.' },
  { compounds: ['nmn', 'pterostilbene'], type: 'synergy',
    title: 'NAD⁺ pathway synergy',
    description: 'NMN raises NAD⁺ levels; pterostilbene activates sirtuins (SIRT1) that require NAD⁺ as a cofactor. Together they maximise NAD⁺-dependent pathways for cellular maintenance and neuroprotection.' },
  { compounds: ['vitamin-d3', 'omega-3'], type: 'synergy',
    title: 'Anti-inflammatory synergy',
    description: 'Both reduce neuroinflammation via different pathways — Vitamin D3 via VDR-mediated gene regulation, omega-3 via eicosanoid pathway modulation. Complementary anti-inflammatory support.' },
  { compounds: ['sulbutiamine', 'alpha-gpc'], type: 'synergy',
    title: 'Cholinergic and energy support',
    description: 'Sulbutiamine boosts thiamine-dependent mitochondrial function and modulates cholinergic transmission; Alpha-GPC provides direct choline supply — complementary support for focus and memory.' },

  // ── CAUTIONS ──────────────────────────────────────────────

  { compounds: ['5-htp', 'l-tryptophan'], type: 'caution',
    title: 'Redundant serotonin loading',
    description: 'Both are serotonin precursors (L-Tryptophan → 5-HTP → Serotonin). Taking both together is redundant and risks excessive serotonin activity (nausea, GI issues, rare serotonin syndrome risk). Choose one.' },

  { compounds: ['huperzine-a', 'alpha-gpc'], type: 'caution',
    title: 'Potential excess acetylcholine',
    description: 'Huperzine A inhibits AChE (slows ACh breakdown); Alpha-GPC increases ACh synthesis. Combined effect can cause excess ACh: muscle twitching, GI cramps, sweating, and cognitive fog. Use lower doses of each if stacking deliberately.' },
  { compounds: ['huperzine-a', 'citicoline'], type: 'caution',
    title: 'Potential excess acetylcholine',
    description: 'Huperzine A\'s AChE inhibition combined with citicoline\'s choline supply can raise ACh beyond the therapeutic window. Monitor for cholinergic symptoms and reduce doses.' },
  { compounds: ['huperzine-a', 'bacopa'], type: 'caution',
    title: 'Additive AChE inhibition',
    description: 'Both inhibit acetylcholinesterase — bacosides reversibly, huperzine A selectively. Additive AChE inhibition risks excessive acetylcholine if other cholinergic compounds are also present.' },
  { compounds: ['huperzine-a', 'alcar'], type: 'caution',
    title: 'Additive cholinergic effect',
    description: 'ALCAR donates acetyl groups to ACh synthesis while huperzine A prevents ACh breakdown — combined effect raises ACh levels from both directions. Risk of excess ACh symptoms at high doses.' },

  { compounds: ['modafinil', 'caffeine'], type: 'caution',
    title: 'Overstimulation risk',
    description: 'At high caffeine doses (200+ mg), the combination with modafinil can cause anxiety, elevated heart rate, and overstimulation. Low-dose caffeine (50–100 mg) is commonly used with modafinil without issue.' },
  { compounds: ['phenylpiracetam', 'caffeine'], type: 'caution',
    title: 'Additive stimulation',
    description: 'Phenylpiracetam has stimulant properties via catecholamine reuptake inhibition. Adding caffeine increases the risk of anxiety, palpitations, and overstimulation.' },
  { compounds: ['phenylpiracetam', 'modafinil'], type: 'caution',
    title: 'Additive stimulation',
    description: 'Both phenylpiracetam and modafinil are stimulating — combining them significantly increases the risk of anxiety and cardiovascular strain with no established additional cognitive benefit.' },

  { compounds: ['melatonin', '5-htp'], type: 'caution',
    title: 'Additive serotonergic and sedating effect',
    description: 'Melatonin is downstream of serotonin (serotonin → N-acetylserotonin → melatonin). 5-HTP raises serotonin, which may increase melatonin production. Together they produce additive sedation — appropriate only for nighttime sleep support.' },
  { compounds: ['melatonin', 'gaba'], type: 'caution',
    title: 'Additive sedation',
    description: 'Both produce sedating and sleep-promoting effects. The combination is only appropriate for nighttime use — can cause excessive grogginess and impair morning cognitive function.' },

  { compounds: ['mucuna-pruriens', '5-htp'], type: 'caution',
    title: 'Competing enzyme pathway',
    description: 'L-DOPA (from Mucuna) and 5-HTP compete for aromatic amino acid decarboxylase (AADC) — the enzyme that converts both to dopamine and serotonin respectively. High doses of both can reduce the effectiveness of each.' },
  { compounds: ['mucuna-pruriens', 'l-tryptophan'], type: 'caution',
    title: 'Competing enzyme pathway',
    description: 'L-DOPA and L-Tryptophan compete for BBB transport (large neutral amino acid transporter) and downstream enzymatic conversion. High combined doses may reduce efficacy of both.' },
];
